# Generated by Django 4.2.2 on 2023-06-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('researcher_name', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('collector_name', models.CharField(max_length=100)),
                ('collection_location', models.CharField(max_length=100)),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('depth', models.IntegerField()),
                ('sediment_type', models.CharField(max_length=100)),
                ('specimen_size', models.IntegerField()),
                ('photo_material', models.CharField(max_length=100)),
            ],
        ),
    ]
